version: '2'
services:
  netmuxd:
    container_name: netmuxd
    build:
      context: .
      dockerfile: docker/netmuxd.dockerfile
    command: -c "cp /output/* /oput && chmod +x /oput/*"
    image: netmuxd:latest
    depends_on:
      - usbmuxd
    volumes:
      - ./bin:/oput

  altserver:
    container_name: altserver
    build:
      context: .
      dockerfile: docker/altserver.dockerfile
    command: sh -c "cp /buildenv/altserver/AltServer-Linux/AltServer-* /build/altserver && chmod +x /build/altserver || return 0"
    image: altserver:latest
    volumes:
      - ./bin:/build

  usbmuxd:
    container_name: usbmuxd
    build:
      context: .
      dockerfile: docker/usbmuxd.dockerfile
    image: usbmuxd:latest

  # avahi:
  #   container_name: avahi
  #   build:
  #     context: .
  #     dockerfile: docker/avahi.dockerfile
  #   image: avahi:latest
  #   network_mode: host
  #   volumes:
  #     - /dev/bus/usb:/dev/bus/usb
  #     - /var/lib/lockdown:/var/lib/lockdown
  #     - /var/run:/var/run
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #
  #  config:
  #    build: docker
  #    container_name: altserver_config
  #    volumes:
  #      - /dev/bus/usb:/dev/bus/usb
  #      - /var/lib/lockdown:/var/lib/lockdown
  #      - /var/run:/var/run
  #      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #      - ./bin:/altbin
  #    privileged: true
  #    stdin_open: true
  #    network_mode: host
  #    tty: true
  #    command: -c "/bin/bash"
  #
  daemon:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: daemon
    image: daemon:latest
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /var/lib/lockdown:/var/lib/lockdown
      - /var/run:/var/run
      - ./bin:/app/bin
    privileged: true
    depends_on:
      - netmuxd
      - altserver
      - usbmuxd
    network_mode: host
    restart: unless-stopped
    command: ./run.sh
